#*************************************************************************************
# Pontificia Universidad Javeriana                                                  *
# Fecha: 16 de Octubre del 2025                                                     *
# Autor: Daniel Felipe Ramirez Vargas                                               *
# Materia: Sistemas Operativos                                                      *
# Tema: Implementacion de productor consumidor a partir de Pipe Named               *
# Descripcion:                                                                      *
#  -Archivo servidor que permite                                                    *
#************************************************************************************/

GCC = gcc
FLAGS =
MODULO =
DIRECTORIO = Ejecutables

PROGRAMAS = hilos

hilos_pthread01:
	mkdir -p $(DIRECTORIO)
	$(GCC) $@.c -o $(DIRECTORIO)/$@
clear:
	$(RM) -rf $(DIRECTORIO)

