#*************************************************************************************
# Pontificia Universidad Javeriana                                                  *
# Fecha: 16 de Octubre del 2025                                                     *
# Autor: Daniel Felipe Ramirez Vargas                                               *
# Materia: Sistemas Operativos                                                      *
# Tema: Implementacion de productor consumidor a partir de Pipe Named               *
# Descripcion:                                                                      *
#  -Archivo servidor que permite                                                    *
#************************************************************************************/

GCC = gcc
FLAGS = -lpthread
MODULO =
DIRECTORIO = Ejecutables

PROGRAMAS = hilos

lab_pthread00_Ramirez:
	mkdir -p $(DIRECTORIO)
	$(GCC) $@.c -o $(DIRECTORIO)/$@ $(FLAGS)
lab_pthread01_Ramirez:
	mkdir -p $(DIRECTORIO)
	$(GCC) $@.c -o $(DIRECTORIO)/$@ $(FLAGS)
lab_pthread02_Ramirez:
	mkdir -p $(DIRECTORIO)
	$(GCC) $@.c -o $(DIRECTORIO)/$@ $(FLAGS)
clear:
	$(RM) -rf $(DIRECTORIO)

